--- #YAML:1.0
name:                Graph-Timeline
version:             1.5
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Date::Calc:                    0
    GD:                            0
    GD::Text:                      0
    GD::Text::Wrap:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
